modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "palladium"
version = "${version}"
displayName = "Palladium"
authors = "Lucraft"
description = '''
Core mod for all ThreeTAG mods.
'''
logoFile = "palladium_banner.png"
logoBlur = false
displayURL = "https://modrinth.com/project/threetag-palladium"
updateJSONURL = "https://squirrelcontrol.threetag.net/api/forge_updates/threetag-palladium"

[[dependencies.palladium]]
modId = "neoforge"
behaviour = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "architectury"
behaviour = "required"
versionRange = "[15.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "minecraft"
behaviour = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "palladium.mixins.json"

[[mixins]]
config = "palladium-neoforge.mixins.json"
